services:
  bot:
    build: .
    container_name: yoshlar_ittifoqi_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/bot_database.db
